version: "3.7"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-delayed-artistic-guppy
    container_name: ldag
    restart: on-failure
    working_dir: /var/www/
    volumes:
      - ./:/var/www:cached
    tty: true
